//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Norem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champions.
        /// </summary>
        internal static string Champion {
            get {
                return ResourceManager.GetString("Champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DefaultPasswordTextBox {
            get {
                return ResourceManager.GetString("DefaultPasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string DefaultUsernameTextBox {
            get {
                return ResourceManager.GetString("DefaultUsernameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forglar Swamp.
        /// </summary>
        internal static string ForglarSwamp {
            get {
                return ResourceManager.GetString("ForglarSwamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forsaken Wastes.
        /// </summary>
        internal static string ForsakenWastes {
            get {
                return ResourceManager.GetString("ForsakenWastes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ironfist Stronghold.
        /// </summary>
        internal static string IronfistStronghold {
            get {
                return ResourceManager.GetString("IronfistStronghold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K&apos;Thir Forest.
        /// </summary>
        internal static string KThirForest {
            get {
                return ResourceManager.GetString("KThirForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem logging in..
        /// </summary>
        internal static string LoginErrorLabel {
            get {
                return ResourceManager.GetString("LoginErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string RarityCommon {
            get {
                return ResourceManager.GetString("RarityCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic.
        /// </summary>
        internal static string RarityExotic {
            get {
                return ResourceManager.GetString("RarityExotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        internal static string RarityLegendary {
            get {
                return ResourceManager.GetString("RarityLegendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited.
        /// </summary>
        internal static string RarityLimited {
            get {
                return ResourceManager.GetString("RarityLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string RarityRare {
            get {
                return ResourceManager.GetString("RarityRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        internal static string RarityUncommon {
            get {
                return ResourceManager.GetString("RarityUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relics.
        /// </summary>
        internal static string Relic {
            get {
                return ResourceManager.GetString("Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savage Tundra.
        /// </summary>
        internal static string SavageTundra {
            get {
                return ResourceManager.GetString("SavageTundra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shattered Peaks.
        /// </summary>
        internal static string ShatteredPeaks {
            get {
                return ResourceManager.GetString("ShatteredPeaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        internal static string Spell {
            get {
                return ResourceManager.GetString("Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sundered Lands.
        /// </summary>
        internal static string SunderedLands {
            get {
                return ResourceManager.GetString("SunderedLands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underdepths.
        /// </summary>
        internal static string Underdepths {
            get {
                return ResourceManager.GetString("Underdepths", resourceCulture);
            }
        }
    }
}
